// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQLUHTHhGq468a11gW76aF27CKY04r8Hk',
    appId: '1:439628553649:web:09dad1a8061a855b44b190',
    messagingSenderId: '439628553649',
    projectId: 'iedeo-43e6a',
    authDomain: 'iedeo-43e6a.firebaseapp.com',
    storageBucket: 'iedeo-43e6a.firebasestorage.app',
    measurementId: 'G-P6Z26SMSLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAApBzsE0Jq1qEpVeMiERRWTEZfC8gZzMA',
    appId: '1:439628553649:android:20b25fe0bf8d853644b190',
    messagingSenderId: '439628553649',
    projectId: 'iedeo-43e6a',
    storageBucket: 'iedeo-43e6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcxapdWguDJssP84pFwolciZ3wCDchl6U',
    appId: '1:439628553649:ios:14f77a439350abbf44b190',
    messagingSenderId: '439628553649',
    projectId: 'iedeo-43e6a',
    storageBucket: 'iedeo-43e6a.firebasestorage.app',
    iosClientId: '439628553649-97bro65kbmrv42it9t94r0u7l4bndfj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyRoutineFollowTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcxapdWguDJssP84pFwolciZ3wCDchl6U',
    appId: '1:439628553649:ios:14f77a439350abbf44b190',
    messagingSenderId: '439628553649',
    projectId: 'iedeo-43e6a',
    storageBucket: 'iedeo-43e6a.firebasestorage.app',
    iosClientId: '439628553649-97bro65kbmrv42it9t94r0u7l4bndfj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyRoutineFollowTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQLUHTHhGq468a11gW76aF27CKY04r8Hk',
    appId: '1:439628553649:web:226305661b750aea44b190',
    messagingSenderId: '439628553649',
    projectId: 'iedeo-43e6a',
    authDomain: 'iedeo-43e6a.firebaseapp.com',
    storageBucket: 'iedeo-43e6a.firebasestorage.app',
    measurementId: 'G-G2WPGPJ6GH',
  );
}
